#!/usr/bin/env bash
# Display information about subdomains

get()
{
    if [ -z "$2" ]
    then
        www_ip="$(dig "www.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tr -d '\n')"
        lb_ip="$(dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tr -d '\n')"
        w01_ip="$(dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tr -d '\n')"
        w02_ip="$(dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tr -d '\n')"

        www_rec="$(dig "www.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tr -d '\n')"
        lb_rec="$(dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tr -d '\n')"
        w01_rec="$(dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tr -d '\n')"
        w02_rec="$(dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tr -d '\n')"

        echo "The subdomain www is a $www_rec record and points to $www_ip"
		echo "The subdomain lb-01 is a $lb_rec record and points to $lb_ip"
		echo "The subdomain web-01 is a $w01_rec record and points to $w01_ip"
		echo "The subdomain web-02 is a $w02_rec record and points to $w02_ip"
    
    elif [ "$2" ]
    then
        sub="$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $1}' | tr -d '\n;' | cut -d'.' -f1)"
		record="$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tr -d '\n')"
		ip="$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tr -d '\n')"
		echo "The subdomain $sub is a $record record and points to $ip"
    fi
}

get "$1" "$2"
exit 0
