#!/usr/bin/env bash
# comment
file='/var/run/my_process.pid'

if [[ $1 == "start" ]]
then
    touch "$file"
    bash ./manage_my_process &
    echo "$!" > "$file"
    echo "manage_my_process started"
elif [[ $1 == "stop" ]]
then
    kill "$(cat "$file")"
    rm "$file"
    echo "manage_my_process stopped"
elif [[ $1 == "restart" ]]
then
    kill "$(cat "$file")"
    rm "$file"
    touch "$file"
    bash ./manage_my_process &
    echo "$!" > "$file"
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
