#!/usr/bin/env bash
# Tell the story of passwd

IFS=:
while read -r user pass uid gid uinfo home cmd
do
    echo "The user $user is part of the $gid gang, lives in $home and rides $cmd. $uid's place is protected by the passcode $pass, more info about the user here: $uinfo"
done < /etc/passwd