#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

i=1

while (( "$i" < 11))
do
    if (( "$i" == 10 ))
    then
        echo "Hi"
    else
        echo "Holberton School"
    fi
    (( i++ ))
done
