#!/usr/bin/env bash
# This script is displaying  the time for 12 hours and 59 minutes

echo "Hour: 0"
for (( i=1; i <=12; i++ ))
do
    for (( j=1; j<=60; j++ ))
    do
        if (( "$j" == 60 ))
        then
            echo "Hour: $i"
        else
            echo "$j"
        fi
    done
done
